### ISSUE TITLE
throwA does not work when the result type of the method being tested is Map

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#10]
```
What steps will reproduce the problem?

Example spec:

object ThrowExceptionSpec extends Specification {

  def methodWithMapResult: Map[String, String] = throw new
IllegalArgumentException

  def methodWithBooleanResult: Boolean = throw new IllegalArgumentException

  "exceptions thrown should be handled" should {
    "tested method result is Boolean" in {
      methodWithBooleanResult must throwA(new IllegalArgumentException)
    }
    "tested method result is Map" in {
      methodWithMapResult must throwA(new IllegalArgumentException)
    }
  }
}

What is the expected output? What do you see instead?

I expect both tests to pass, but only the first one does.

The test that fails gives the following output:

tested method result is Map(org.specs.runner.ExampleTestCase)  Time
elapsed: 0.003 sec  <<< FAILURE!
java.lang.IllegalArgumentException
        at
test.ThrowExceptionSpec$.methodWithMapResult(ThrowExceptionTest.scala:10)
        at
test.ThrowExceptionSpec$$anonfun$1$$anonfun$apply$4.apply(ThrowExceptionTest.sca
la:19)
        at
test.ThrowExceptionSpec$$anonfun$1$$anonfun$apply$4.apply(ThrowExceptionTest.sca
la:19)
        at
org.specs.specification.ExampleLifeCycle$class.executeTest(SpecificationStructur
e.scala:130)
        at org.specs.Specification.executeTest(Specs.scala:24)
        at org.specs.Sut.executeTest(Specs.scala:151)
        at org.specs.Example.in(Specs.scala:219)
        at
test.ThrowExceptionSpec$$anonfun$1.apply(ThrowExceptionTest.scala:18)
        at
test.ThrowExceptionSpec$$anonfun$1.apply(ThrowExceptionTest.scala:14)
        at org.specs.Sut.should(Specs.scala:107)
        at test.ThrowExceptionSpec$.<init>(ThrowExceptionTest.scala:14)
        at test.ThrowExceptionSpec$.<clinit>(ThrowExceptionTest.scala)
        at test.ThrowExceptionTest.<init>(ThrowExceptionTest.scala:6)

What version of the product are you using? On what operating system?
specs 1.2.2
```

Original issue reported on code.google.com by `ismaelj` on 8 Feb 2008 at 7:03

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I don't know yet how to fix this but here's a workaround:

{methodWithMapResult; ()} must throwA(new IllegalArgumentException)
```

Original comment by `etorrebo...@gmail.com` on 9 Feb 2008 at 1:14
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Ok, I fixed it and deployed on the snapshot server. I will add test cases for 
that
before releasing.
```

Original comment by `etorrebo...@gmail.com` on 9 Feb 2008 at 1:28
- Changed state: **Fixed**

Attachments:
- [specs-1.2.3-SNAPSHOT.jar](https://storage.googleapis.com/google-code-attachments/specs/issue-10/comment-2/specs-1.2.3-SNAPSHOT.jar)

**Comment by GoogleCodeExporter** [comment]
```
Sorry, that's not fixed really,... I thought I had. With what has been 
committed you
would have to write:

theValue(methodWithMapResult) must throwA(new IllegalArgumentException) 

or the previous work-around. Otherwise you would get a compilation error saying 
that
2 implicit conversions apply. I'll see what I can do but I am not sure there's 
a real
way  to avoid this.
```

Original comment by `etorrebo...@gmail.com` on 9 Feb 2008 at 1:40
- Changed state: **Started**

Attachments:
- [](https://storage.googleapis.com/google-code-attachments/specs/issue-10/comment-3/)

**Comment by GoogleCodeExporter** [comment]
```
I've tested this and wrapping the method call with theValue works. It would be 
nice
if it was possible to be consistent, but the workaround doesn't seem too bad. I 
would
recommend adding a note in the matchers wiki page explaining in what situations 
it's
required though.

I've seen an issue with the recently released scala 2.7.0-rc1 and will report 
that
separately (not sure if it's a Scala or specs problem).
```

Original comment by `ismaelj` on 9 Feb 2008 at 1:58

**Comment by GoogleCodeExporter** [comment]
```
I had a good insight over the night,...

You can test the latest snapshot.
```

Original comment by `etorrebo...@gmail.com` on 10 Feb 2008 at 12:13
- Changed state: **Fixed**

Attachments:
- [specs-1.2.3-SNAPSHOT.jar](https://storage.googleapis.com/google-code-attachments/specs/issue-10/comment-5/specs-1.2.3-SNAPSHOT.jar)

**Comment by GoogleCodeExporter** [comment]
```
Great. :) I've tested it and it works (with scala 2.7.0-rc1), thanks.

For future reference, I also use maven so feel free not to upload the snapshot 
jar.
```

Original comment by `ismaelj` on 10 Feb 2008 at 3:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 11 Feb 2008 at 1:45
- Changed state: **Verified**
