### ISSUE TITLE
Enhancement: run rows of data tables isolated

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#116]
```
I love the specs framework and one of its major advantages for me are data 
tables. Now the 
problem I face is that the before and after actions (or example contexts) are 
not invoked/(re-
)initialized around each row in a data table. That way, if one test (using the 
data in one row) 
modifies the SUT, the next test (using the data in the next row) may be 
influenced by the previous 
test and produce an incorrect outcome.

If you could add a simple way to have contexts initialized around the rows in a 
data table, that 
would really rock.

Thanks for all your efforts!
```

Original issue reported on code.google.com by `asfli...@googlemail.com` on 6 Feb 2010 at 1:27

**Comment by GoogleCodeExporter** [comment]
```
Hi Andreas,

I'll have a look at that. However, I've been thinking about it though and I 
think 
that it would need to be declarative more than implicit. That's because when 
you are 
inside the body of an example the context setup is supposed to have already 
been 
executed.

So I think that I will try to provide a way to setup a context on the 
DataTable, and 
better to declare that this datatable should reuse the SUS context.

I need to take care of issue 117 first and I'll let you know my progress on 
this 
matter. Note also that I plan to provide this capability only in specs for 
2.8.0 
because maintaining 2 branches is too time-consuming at the moment and Scala 
2.8.0 is 
announced for next month.
```

Original comment by `etorrebo...@gmail.com` on 8 Feb 2010 at 11:51
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Hi Eric, 

thanks for looking into it. The declarative approach sounds perfect to me. Btw. 
I have a similar problem when I 
use things like SomeEnum.foreach(x => mutateState(x) must beTrue) inside an 
example, it's hard to get the 
single enum cases isolated. But maybe I am approaching this the wrong way.

-Andreas
```

Original comment by `asfli...@googlemail.com` on 8 Feb 2010 at 9:40

**Comment by GoogleCodeExporter** [comment]
```
Just to elaborate, with "hard" I meant "verbose" :-)
```

Original comment by `asfli...@googlemail.com` on 8 Feb 2010 at 9:46

**Comment by GoogleCodeExporter** [comment]
```
Could you please send me a small enum example? I'm not sure that I understand 
why there 
is mutation involved in a "real" case.

Thanks.
```

Original comment by `etorrebo...@gmail.com` on 10 Feb 2010 at 2:05

**Comment by GoogleCodeExporter** [comment]
```
Here's a small excerpt from a spec for a little game attempt of mine. You can 
find the whole file at 
http://github.com/aydjen/ecidice/blob/master/src/spec/scala/ecidice/model/Moveme
ntRefereeSpec.scala

  "allow a player to move in any direction with a floor dice from the center" in {
      for (somewhere <- Direction.values) within (simpleGame) {
        placePlayer(p1, (1, 1))
        val d1 = placeDice(1, 1)

        game.controlReferee.requestControl(p1) aka "control request" mustEqual Some(d1)
        game.movementReferee.requestMove(p1, somewhere) aka "move " + somewhere must beTrue
      }
    }

What is going on here is that I want to test that a player that controls a dice 
can move from the center of the 
board to any of the directions in the enum. Obviously both the placement of 
dice and player, as well as the 
movement mutates the game's state. Thus, I need to reset the board to an empty 
state before each enum 
value.

The "simpleGame" used to be a spec context that I passed lazily evaluate to my 
own method which called the 
context's beforeActions, then the passed function object and lastly the 
context's afterActions. But somewhere 
in the last updates, those actions went private, so I had to declare my own 
context now and also added an 
implicit conversion to a spec context so I can reuse the same fixture. 

Thanks for looking at this. :)
```

Original comment by `asfli...@googlemail.com` on 10 Feb 2010 at 7:38

**Comment by GoogleCodeExporter** [comment]
```
> But somewhere in the last updates, those actions went private

I'm thinking of revisiting this to allow a better reuse of Contexts in the 
future.

Now, about the side-effects inside the example, one thing that you could do is 
to 
create sub examples:

"allow a player to move in any direction with a floor dice from the center" in {
  for (somewhere <- Direction.values) {
    placePlayer(p1, (1, 1))
    val d1 = placeDice(1, 1)
    "from the center to " + somewhere >> {
      game.controlReferee.requestControl(p1) aka "control request" mustEqual Some(d1)
      game.movementReferee.requestMove(p1, somewhere) aka "move " + somewhere must 
beTrue
    }
  }
}

Given that local variables are re-initialized for each example and sub-example, 
you 
may not even need contexts as an object and just write at the beginning of your 
specification:

val (board, game) = (new Board(3, 3), new Game(2, board))
val (p1, p2) = (game.players(0), = game.players(1))

The added advantage of using sub-examples is to isolate the failure if the move 
fails 
in just one direction.

Thanks for trying this out and telling me if it works and suits you.
```

Original comment by `etorrebo...@gmail.com` on 10 Feb 2010 at 9:26

**Comment by GoogleCodeExporter** [comment]
```
Wow, great! I knew there was something I hadn't thought of. Works smooth as 
silk if I also draw the placement 
of player and dice into the sub-example.

Thanks a lot for the suggestion. Makes the spec a bit cleaner and the outcome 
report even more detailed.
Awesome.
```

Original comment by `asfli...@googlemail.com` on 10 Feb 2010 at 9:56

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r1253.
```

Original comment by `etorrebo...@gmail.com` on 3 Mar 2010 at 11:00
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hi Andreas,

Please try the latest version and have a look at: 
http://code.google.com/p/specs/wiki/AdvancedSpecifications#DataTable_contexts

Then tell me if it fits your requirements.

Thanks.

```

Original comment by `etorrebo...@gmail.com` on 4 Mar 2010 at 12:47

**Comment by GoogleCodeExporter** [comment]
```
Hi,

the change looks great, but I have trouble trying it at the moment: the patch 
happened in trunk, which, if I 
understand correctly, is on scala 2.7.7 (or am I missing something again?). 
I've already migrated all my scala 
stuff to 2.8 so I have some trouble trying this out with my projects. 
Nonetheless, from looking at your change 
and its tests, this seems to be exactly what I needed. 

Thanks so much for adding it!
```

Original comment by `asfli...@googlemail.com` on 4 Mar 2010 at 7:24

**Comment by GoogleCodeExporter** [comment]
```
Hi Andreas,

I also made that change for 2.8. You should be able to get it from there:

http://nexus.scala-tools.org/content/repositories/snapshots/org/scala-
tools/testing/specs_2.8.0.Beta1/1.6.4-SNAPSHOT
```

Original comment by `etorrebo...@gmail.com` on 4 Mar 2010 at 7:57

**Comment by GoogleCodeExporter** [comment]
```
Hello Eric,

It seemed to work fine at first. I added different contexts to some tables. For 
some reason that I have been 
unable to trace, I am running into a NullPointerException if I add it to one of 
my data tables. Strangely, if that 
one fails with the NPE, 2 other tables, one of them very very unrelated, start 
failing with a similar NPE, too.

I am currently unable to provide a clean case to reproduce it. In case you want 
to have a look anyway, I've put 
the failing stuff on github:
http://github.com/aydjen/ecidice/blob/master/src/spec/scala/ecidice/model/BoardS
pec.scala
The first data table in that file is causing the problems, i.e. if I comment 
away line 64, the whole spec passes.

Here's the stack trace:

org.specs.runner.UserError: java.lang.NullPointerException: null
    at org.specs.util.TableHeader.reflMethod$Method2(DataTable.scala:93)
    at org.specs.util.TableHeader.$bar$greater(DataTable.scala:93)
    at ecidice.model.BoardSpec$$anonfun$2$$anonfun$apply$9.apply(BoardSpec.scala:65)
    at ecidice.model.BoardSpec$$anonfun$2$$anonfun$apply$9.apply(BoardSpec.scala:69)
    at org.specs.specification.LifeCycle$class.withCurrent(ExampleLifeCycle.scala:60)
    at org.specs.specification.Examples.withCurrent(Examples.scala:52)
    at org.specs.specification.Examples$$anonfun$specifyExample$1.apply(Examples.scala:108)
    at org.specs.specification.Examples$$anonfun$specifyExample$1.apply(Examples.scala:108)
    at 
org.specs.specification.ExampleExecution$$anonfun$3$$anonfun$apply$5.apply(Examp
leLifeCycle.scala:214)
    at scala.Option.getOrElse(Option.scala:59)
    at org.specs.specification.LifeCycle$class.executeExpectations(ExampleLifeCycle.scala:82)
    at org.specs.specification.BaseSpecification.executeExpectations(BaseSpecification.scala:58)
    at org.specs.specification.LifeCycle$$anonfun$executeExpectations$1.apply(ExampleLifeCycle.scala:82)
    at org.specs.specification.LifeCycle$$anonfun$executeExpectations$1.apply(ExampleLifeCycle.scala:82)
    at scala.Option.map(Option.scala:74)
    at org.specs.specification.LifeCycle$class.executeExpectations(ExampleLifeCycle.scala:82)
    at org.specs.specification.BaseSpecification.executeExpectations(BaseSpecification.scala:58)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2$$anonfun$a
pply$3$$anonfun$ap
ply$4.apply(ExampleContext.scala:73)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2$$anonfun$a
pply$3$$anonfun$ap
ply$4.apply(ExampleContext.scala:73)
    at scala.Option.map(Option.scala:74)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2$$anonfun$a
pply$3.apply(Example
Context.scala:73)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2$$anonfun$a
pply$3.apply(Example
Context.scala:73)
    at org.specs.specification.ExampleContext$class.id$1(ExampleContext.scala:32)
    at org.specs.specification.ExampleContext$$anonfun$1.apply(ExampleContext.scala:33)
    at org.specs.specification.ExampleContext$$anonfun$1.apply(ExampleContext.scala:33)
    at org.specs.specification.BeforeAfter$$anonfun$newActions$1$1.apply(Context.scala:88)
    at org.specs.specification.Context.id$1(Context.scala:343)
    at org.specs.specification.Context$$anonfun$15.apply(Context.scala:344)
    at org.specs.specification.Context$$anonfun$15.apply(Context.scala:344)
    at 
org.specs.specification.Contexts$$anonfun$org$specs$specification$Contexts$$tran
sferActionsToSus$3.appl
y(Context.scala:217)
    at 
org.specs.specification.Contexts$$anonfun$org$specs$specification$Contexts$$tran
sferActionsToSus$3.appl
y(Context.scala:217)
    at org.specs.specification.BeforeAfter$class.newActions$1(Context.scala:88)
    at org.specs.specification.BeforeAfter$$anonfun$stackAround$1.apply(Context.scala:91)
    at org.specs.specification.BeforeAfter$$anonfun$stackAround$1.apply(Context.scala:91)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2.apply(Exam
pleContext.scala:73)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2.apply(Exam
pleContext.scala:72)
    at scala.Option.map(Option.scala:74)
    at org.specs.specification.ExampleContext$class.executeExpectations(ExampleContext.scala:72)
    at org.specs.specification.Examples.executeExpectations(Examples.scala:52)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2$$anonfun$a
pply$3$$anonfun$ap
ply$4.apply(ExampleContext.scala:73)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2$$anonfun$a
pply$3$$anonfun$ap
ply$4.apply(ExampleContext.scala:73)
    at scala.Option.map(Option.scala:74)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2$$anonfun$a
pply$3.apply(Example
Context.scala:73)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2$$anonfun$a
pply$3.apply(Example
Context.scala:73)
    at org.specs.specification.ExampleContext$class.id$1(ExampleContext.scala:32)
    at org.specs.specification.ExampleContext$$anonfun$1.apply(ExampleContext.scala:33)
    at org.specs.specification.ExampleContext$$anonfun$1.apply(ExampleContext.scala:33)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2.apply(Exam
pleContext.scala:73)
    at 
org.specs.specification.ExampleContext$$anonfun$executeExpectations$2.apply(Exam
pleContext.scala:72)
    at scala.Option.map(Option.scala:74)
    at org.specs.specification.ExampleContext$class.executeExpectations(ExampleContext.scala:72)
    at org.specs.specification.Examples.executeExpectations(Examples.scala:52)
    at org.specs.specification.ExampleExecution$$anonfun$3.apply(ExampleLifeCycle.scala:214)
    at org.specs.specification.ExampleExecution$$anonfun$3.apply(ExampleLifeCycle.scala:193)
    at org.specs.specification.ExampleExecution$$anonfun$2.apply(ExampleLifeCycle.scala:176)
    at org.specs.specification.ExampleExecution.execute(ExampleLifeCycle.scala:247)
    at 
org.specs.specification.SpecificationExecutor$$anonfun$executeExample$1.apply(Sp
ecificationExecutor.scala:
55)
    at 
org.specs.specification.SpecificationExecutor$$anonfun$executeExample$1.apply(Sp
ecificationExecutor.scala:
55)
    at scala.Option.map(Option.scala:74)
    at org.specs.specification.SpecificationExecutor$class.executeExample(SpecificationExecutor.scala:55)
    at org.specs.specification.BaseSpecification.executeExample(BaseSpecification.scala:58)
    at org.specs.specification.BaseSpecification.executeExample(BaseSpecification.scala:58)
    at 
org.specs.specification.ExampleLifeCycle$$anonfun$executeExample$1.apply(Example
LifeCycle.scala:120)
    at 
org.specs.specification.ExampleLifeCycle$$anonfun$executeExample$1.apply(Example
LifeCycle.scala:120)
    at scala.Option.map(Option.scala:74)
    at org.specs.specification.ExampleLifeCycle$class.executeExample(ExampleLifeCycle.scala:120)
    at org.specs.specification.Examples.executeExample(Examples.scala:52)
    at org.specs.specification.Examples.executeExample(Examples.scala:52)
    at org.specs.specification.Examples$$anonfun$executeExamples$1.apply(Examples.scala:80)
    at org.specs.specification.Examples$$anonfun$executeExamples$1.apply(Examples.scala:80)
    at scala.Option.map(Option.scala:74)
    at org.specs.specification.Examples.executeExamples(Examples.scala:80)
    at org.specs.specification.ExampleStructure$class.ownSkipped(ExampleStructure.scala:60)
    at org.specs.specification.Examples.ownSkipped(Examples.scala:52)
    at org.specs.runner.ExampleTestCase.run(JUnit.scala:185)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.specs.runner.JUnitSuite$class.run(JUnit.scala:62)
    at org.specs.runner.ExamplesTestSuite.run(JUnit.scala:172)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.specs.runner.JUnitSuite$class.run(JUnit.scala:62)
    at org.specs.runner.JUnit3.run(JUnit.scala:124)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.specs.runner.JUnitSuite$class.run(JUnit.scala:62)
    at org.specs.runner.JUnit4.run(JUnit.scala:132)
    at org.specs.runner.JUnitSuiteRunner.run(JUnitSuiteRunner.scala:45)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

```

Original comment by `asfli...@googlemail.com` on 4 Mar 2010 at 9:34

**Comment by GoogleCodeExporter** [comment]
```
This looks like a compiler bug.

I had a look at the failing method (reflMethod$Method2):

    public static Method reflMethod$Method2(Class class1)
    {
        if((MethodCache)reflPoly$Cache2.get() == null)
            reflPoly$Cache2 = new SoftReference(new EmptyMethodCache());
        Method method2 = ((MethodCache)reflPoly$Cache2.get()).find(class1);
        if(method2 != null)
        {
            return method2;
        } else
        {
            method2 = class1.getMethod("header_$eq", reflParams$Cache2);
            reflPoly$Cache2 = new 
SoftReference(((MethodCache)reflPoly$Cache2.get()).add(class1, method2));
            return method2;
        }
    }

If you compare to what was compiled in Scala 2.7.7, you can see that the 
changes in 
2.8.0 may have introduced a bug:

    public static Method reflMethod$Method1(Class x$1)
    {
        if(reflMethod$Cache1 == null || reflClass$Cache1 != x$1)
        {
            reflMethod$Cache1 = x$1.getMethod("header_$eq", new Class[] {
                org/specs/util/TableHeader
            });
            reflClass$Cache1 = x$1;
        }
        return reflMethod$Cache1;
    }

I think the first method should start with:

        if(reflPoly$Cache2 == null)

and I'm wondering if this is not a manifestation of this ticket:

http://lampsvn.epfl.ch/trac/scala/ticket/1766

BTW, since this is a static method involved that would explain the failure in 
several 
places.

Does that make sense to you?

```

Original comment by `etorrebo...@gmail.com` on 5 Mar 2010 at 7:42

**Comment by GoogleCodeExporter** [comment]
```
Ok, thinking about it, I have removed the structural type I was using and which 
was not 
helping much anyway.

Can you please test again and tell me if it's ok with the latest snapshot?

Thanks.
```

Original comment by `etorrebo...@gmail.com` on 5 Mar 2010 at 10:20

**Comment by GoogleCodeExporter** [comment]
```
Yeah, the explanation kinda makes sense to me :) but where do you get the 
compiled code results from anyway? 
Some kind of bytecode-to-java disassembly?

Anyway, back on topic, I downloaded the latests snapshot jar but it didn't 
verify against sha1 nor md5. Eclipse 
couldn't figure out what to do with it neither, so maybe some kind of corrupt 
upload? I wanted to build from 
source but couldn't find where to check out the 1.6.4 sources from, sorry. :-(
```

Original comment by `asfli...@googlemail.com` on 5 Mar 2010 at 10:59

**Comment by GoogleCodeExporter** [comment]
```
> but where do you get the compiled code results from anyway? 

I decompiled the .class file with a tool called DJ decompiler.

> it didn't verify against sha1

This happened recently that the upload was incorrect, I don't know why.

I just redeployed on http://nexus-direct.scala-
tools.org/content/repositories/snapshots/org/scala-tools/testing/specs_2.8.0.Bet
a1 
(but haven't checked yet the SHA1).

I also committed the 2.8.0 code to svn: 
http://code.google.com/p/specs/source/browse/#svn/branches/SPECS-2.8.0-Beta11.6.
4-
SNAPSHOT
```

Original comment by `etorrebo...@gmail.com` on 5 Mar 2010 at 11:24
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Ah great. Works like a charm now. I'm very happy with the results.

Thanks so much for your assistance through all this. Just as a side note: the 
main reason a colleague of mine 
uses Scala now is that he thinks specs is so incredibly awesome (and so do I, 
btw.). Keep up the cool work!
```

Original comment by `asfli...@googlemail.com` on 6 Mar 2010 at 1:22

**Comment by GoogleCodeExporter** [comment]
```
I'm happy this works for you, thanks for such kind words!
```

Original comment by `etorrebo...@gmail.com` on 6 Mar 2010 at 8:17
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 26 May 2010 at 10:26
- Added labels: **Milestone-1.6.4**
