### ISSUE TITLE
Symbol.intern error when speccing Scalacheck properties

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#13]
```
What steps will reproduce the problem?
1. Scalacheck 1.2
2. Specs 1.2.5
3. Specification such as the one below:

object listSpec extends Specification { 
    "Simple ScalaCheck example" should {
        "have single-item lists" in {
            val listsWithOneInt = for(
                x <- arbitrary[Int]
            ) yield List(x)
            listsWithOneInt must pass { x: List[Int] =>
                x.length must be(1)
            }
        }
    }
}

What is the expected output? What do you see instead?

Expect it to compile and pass.
Running with maven, I instead get:

java.lang.NoSuchMethodError: scala.Symbol.intern()Lscala/Symbol;
    at org.specs.matcher.ScalacheckParameters$class.$init$(ScalacheckMatchers.scala:132)
    at org.specs.matcher.ScalacheckParameters$.<init>(ScalacheckMatchers.scala:198)
    at org.specs.matcher.ScalacheckParameters$.<clinit>(ScalacheckMatchers.scala)
    at 
org.specs.matcher.ScalacheckMatchers$class.defaultParameters(ScalacheckMatchers.
scala:20)
    at org.specs.Specification.defaultParameters(Specs.scala:24)
....


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `awhar...@gmail.com` on 9 Apr 2008 at 5:38

**Comment by GoogleCodeExporter** [comment]
```
This appears to be a version incompatability with post-2.7.0 Scala. In 
particular,
https://lampsvn.epfl.ch/trac/scala/changeset/14055

```

Original comment by `awhar...@gmail.com` on 9 Apr 2008 at 5:48

**Comment by GoogleCodeExporter** [comment]
```
Hi,

The same test is ok for me with both JUnit in Eclipse and Maven. I'm using
scala-2.7.0-final as downloaded by Maven.

When you write "post-2.7.0", you mean that you have this issue with
scala-2.7.0-final? I assume this because the ticket you indicate is before the 
latest
release. 

Eric.
```

Original comment by `etorrebo...@gmail.com` on 9 Apr 2008 at 10:48

**Comment by GoogleCodeExporter** [comment]
```
I had the issue with SNAPSHOT nightlies, but not with 2.7.0-final. Maybe that 
changeset is not related.

```

Original comment by `awhar...@gmail.com` on 10 Apr 2008 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
I will update specs as soon as 2.7.1 is out (the RC-1 has been released 
yesterday).
Is that ok for you to wait for the official new release?
```

Original comment by `etorrebo...@gmail.com` on 11 Apr 2008 at 2:10

**Comment by GoogleCodeExporter** [comment]
```
Now that latest build of Eclipse plugin (beta) from the update site also uses 
version
of Scala that exhibits this problem, it would be great to get specs snapshot 
that
would work with Eclipse plugin even before 2.7.1 is out.
```

Original comment by `mikko.j....@gmail.com` on 14 Apr 2008 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
Hi, 

Sorry for the delay, there is now a 1.2.6-SNAPSHOT release which is compatible 
with
Scala-2.7.1-rc1. You can get it from the [download page
http://code.google.com/p/specs/downloads/list] or from the Maven repository.

Eric.
```

Original comment by `etorrebo...@gmail.com` on 15 Apr 2008 at 1:00
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Yep, works with plugin too. Thanks a lot!

```

Original comment by `mikko.j....@gmail.com` on 15 Apr 2008 at 5:23

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 15 Apr 2008 at 5:36
- Changed state: **Verified**
