### ISSUE TITLE
Code block passed to must be_== evaluated more than once

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#14]
```
What steps will reproduce the problem?

Run the following Specification.

object SpecsSpec extends Specification {
  "specs" should {
    "evaluate a code block only once" in {
      var invoked = 0
      def function = {
        invoked += 1
        assume(invoked == 1)
        invoked
      }
      1 must be_==(function)
    }
  }
}

What is the expected output? What do you see instead?

I expect the test to pass, but it fails with the following exception:

java.lang.AssertionError: assumption failed
    at scala.Predef$.assume(Predef.scala:97)
    at specs.SpecsSpec$$anonfun$1$$anonfun$apply$1.function$1(SpecsTest.scala:15)
    at
specs.SpecsSpec$$anonfun$1$$anonfun$apply$1$$anonfun$apply$3$$anonfun$apply$4.ap
ply(SpecsTest.scala:18)
    at
specs.SpecsSpec$$anonfun$1$$anonfun$apply$1$$anonfun$apply$3$$anonfun$apply$4.ap
ply(SpecsTest.scala:18)
    at org.specs.matcher.AnyMatchers$$anon$3.apply(AnyMatchers.scala:41)
    at org.specs.specification.Assertable$class.applyMatcher(Assert.scala:8)
    at org.specs.specification.Assert.applyMatcher(Assert.scala:23)
    at org.specs.specification.Assert.must(Assert.scala:28)
    at specs.SpecsSpec$$anonfun$1$$anonfun$apply$1.apply(SpecsTest.scala:18)
    at specs.SpecsSpec$$anonfun$1$$anonfun$apply$1.apply(SpecsTest.scala:11)
    at
org.specs.specification.ExampleLifeCycle$class.executeTest(SpecificationStructur
e.scala:142)
    at org.specs.Specification.executeTest(Specs.scala:24)
    at org.specs.Sut.executeTest(Specs.scala:173)
    at org.specs.Example$$anonfun$in$1.apply(Specs.scala:255)
    at org.specs.Example$$anonfun$in$1.apply(Specs.scala:242)
    at org.specs.Example.execute(Specs.scala:277)
    at org.specs.Example.subExamples(Specs.scala:232)
    at
org.specs.runner.ExamplesTestSuite$$anonfun$initialize$2.apply(JUnit.scala:115)
    at
org.specs.runner.ExamplesTestSuite$$anonfun$initialize$2.apply(JUnit.scala:114)
    at scala.Iterator$class.foreach(Iterator.scala:395)
    at
scala.collection.mutable.SingleLinkedList$$anon$1.foreach(SingleLinkedList.scala
:50)
    at scala.Iterable$class.foreach(Iterable.scala:256)
    at scala.collection.mutable.Queue.foreach(Queue.scala:24)
    at org.specs.runner.ExamplesTestSuite.initialize(JUnit.scala:114)
    at org.specs.runner.JUnitSuite$class.init(JUnit.scala:31)
    at org.specs.runner.ExamplesTestSuite.init(JUnit.scala:107)
    at org.specs.runner.JUnitSuite$class.getName(JUnit.scala:40)
    at org.specs.runner.ExamplesTestSuite.getName(JUnit.scala:107)
    at
org.specs.runner.TestDescription$class.asDescription(JUnitSuiteRunner.scala:79)
    at org.specs.runner.JUnitSuiteRunner.asDescription(JUnitSuiteRunner.scala:13)
    at
org.specs.runner.TestDescription$class.makeDescription(JUnitSuiteRunner.scala:87
)
    at
org.specs.runner.JUnitSuiteRunner.makeDescription(JUnitSuiteRunner.scala:13)
    at
org.specs.runner.TestDescription$$anonfun$makeDescription$1.apply(JUnitSuiteRunn
er.scala:89)
    at
org.specs.runner.TestDescription$$anonfun$makeDescription$1.apply(JUnitSuiteRunn
er.scala:88)
    at scala.List.foreach(List.scala:827)
    at
org.specs.runner.TestDescription$class.makeDescription(JUnitSuiteRunner.scala:88
)
    at
org.specs.runner.JUnitSuiteRunner.makeDescription(JUnitSuiteRunner.scala:13)
    at org.specs.runner.JUnitSuiteRunner.getDescription(JUnitSuiteRunner.scala:37)
    at
org.junit.internal.runners.CompositeRunner.getDescription(CompositeRunner.java:4
0)
    at org.junit.runner.Runner.testCount(Runner.java:38)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.countTestCases(J
Unit4TestClassReference.java:29)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.countTests(RemoteTestRunn
er.java:480)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:448)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:673)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java
:386)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.jav
a:196)

What version of the product are you using? On what operating system?

I am running the specs snapshot from Maven from today (02/05/2008).

Please provide any additional information below.

There was a test in my application that started failing this morning
because of this, which would suggest that the regression was introduced
recently. I don't see any commits on SVN though. Is it possible that a new
snapshot was submitted to the repo without committing the changes to SVN?

Btw, I am running the snapshot because I am using Scala 2.7.1-rc2.
```

Original issue reported on code.google.com by `ismaelj` on 2 May 2008 at 1:43

**Comment by GoogleCodeExporter** [comment]
```
Hello, 

Sorry, I indeed introduced a regression with my last commit. My intention was 
to use
lazy parameters for functions creating matchers because when I compose them 
with an
or I don't want the second operand to be evaluated at all if the first one 
succeeds
(see the
[http://code.google.com/p/specs/wiki/MatchersGuide#Matchers_composition_for_obje
ct_graphs_(from_1.2.6)
wiki] for a use of this).

I kept the lazy parameter but I made sure that it was indeed evaluated once. 
You can
test the lasted SNAPSHOT from Maven.

Cheers,

Eric.
```

Original comment by `etorrebo...@gmail.com` on 2 May 2008 at 4:12
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I have verified that issue does not occur with the latest SNAPSHOT.

Thank you for the quick fix (as usual). :)
```

Original comment by `ismaelj` on 2 May 2008 at 5:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 3 May 2008 at 1:22
- Changed state: **Verified**
