### ISSUE TITLE
Missing first / with HtmlSpecification on OSX 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#148]
```
What steps will reproduce the problem?
1. Unzip attachet sbt project
2. sbt reload update test
3. See exception 

What is the expected output? What do you see instead?
 I expect that spec is passed.
 But I see stacktrace:

java.io.FileNotFoundException: 
Volumes/APP/Work/HtmlSpecTest/lib_managed/scala_2.8.0.RC6/compile/specs_2.8.0.RC
6-1.6.5-SNAPSHOT.jar (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:106)
    at java.io.FileInputStream.<init>(FileInputStream.java:66)
    at org.specs.io.FileSystem$class.unjar(FileSystem.scala:216)
    at org.specs.Specification.unjar(Specification.scala:43)
    at org.specs.io.FileSystem$$anonfun$copySpecResourcesDir$1.apply(FileSystem.scala:269)
    at org.specs.io.FileSystem$$anonfun$copySpecResourcesDir$1.apply(FileSystem.scala:266)
    at scala.collection.immutable.Set$Set1.foreach(Set.scala:81)
    at org.specs.io.FileSystem$class.copySpecResourcesDir(FileSystem.scala:266)
    at org.specs.Specification.copySpecResourcesDir(Specification.scala:43)
    at org.specs.runner.Html$class.report(Html.scala:51)
    at org.specs.HtmlSpecification.report(HtmlSpecification.scala:25)
    at org.specs.HtmlSpecification.report(HtmlSpecification.scala:25)
    at org.specs.runner.Reporter$class.reportSpecs(Reporter.scala:195)
    at org.specs.Specification.reportSpecs(Specification.scala:43)
    at org.specs.runner.TestInterfaceRunner.run(TestInterfaceRunner.scala:52)
    at org.specs.runner.TestInterfaceRunner.run(TestInterfaceRunner.scala:45)
    at sbt.TestRunner.run(TestFramework.scala:52)
    at sbt.TestRunner.runTest$1(TestFramework.scala:66)
    at sbt.TestRunner.run(TestFramework.scala:75)
    at sbt.TestFramework$$anonfun$9$$anonfun$apply$11.runTest$2(TestFramework.scala:192)
    at sbt.TestFramework$$anonfun$9$$anonfun$apply$11$$anonfun$apply$12.apply(TestFramework.scala:203)
    at sbt.TestFramework$$anonfun$9$$anonfun$apply$11$$anonfun$apply$12.apply(TestFramework.scala:203)
    at sbt.NamedTestTask.run(TestFramework.scala:91)
    at sbt.ScalaProject$$anonfun$sbt$ScalaProject$$toTask$1.apply(ScalaProject.scala:187)
    at sbt.ScalaProject$$anonfun$sbt$ScalaProject$$toTask$1.apply(ScalaProject.scala:187)
    at sbt.TaskManager$Task.invoke(TaskManager.scala:62)
    at sbt.impl.RunTask.doRun$1(RunTask.scala:77)
    at sbt.impl.RunTask.runTask(RunTask.scala:85)
    at sbt.impl.RunTask.sbt$impl$RunTask$$runIfNotRoot(RunTask.scala:60)
    at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
    at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
    at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
    at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
    at sbt.Control$.trapUnit(Control.scala:19)
    at sbt.Distributor$Run$Worker.run(ParallelRunner.scala:131)


What version of the product are you using? On what operating system?
Spec version - 2.8.0.RC6-1.6.5-SNAPSHOT
Scala version 2.8.0.RC6

java version "1.6.0_20"
Java(TM) SE Runtime Environment (build 1.6.0_20-b02-279-9M3165)
Java HotSpot(TM) 64-Bit Server VM (build 16.3-b01-279, mixed mode)

OS - Mac OSX 10.5.8 Leopard

Please provide any additional information below.

Non HTML specs run without problem.

```

Original issue reported on code.google.com by `kolcha...@gmail.com` on 20 Jun 2010 at 7:48

Attachments:
- [HtmlSpecTest.zip](https://storage.googleapis.com/google-code-attachments/specs/issue-148/comment-0/HtmlSpecTest.zip)

**Comment by GoogleCodeExporter** [comment]
```
I don't have a Mac so this issue may be OS specific here. I'm concerned by the 
exception message: 

java.io.FileNotFoundException: 
Volumes/APP/Work/HtmlSpecTest/lib_managed/scala_2.8.0.RC6/compile/specs_2.8.0.RC
6-1.6.5-SNAPSHOT.jar (No such file or directory)

So I have several questions:

Is the jar file really missing from the compile directory? What happen if you 
add the expected jar file to the directory?
Is the path incorrectly defined? What would be the proper path in that case?
Can you try with Maven to see if things work ok?

```

Original comment by `etorrebo...@gmail.com` on 20 Jun 2010 at 10:42

**Comment by GoogleCodeExporter** [comment]
```
Pproper path  is 
/Volumes/APP/Work/HtmlSpecTest/lib_managed/scala_2.8.0.RC6/compile/specs_2.8.0.R
C6-1.6.5-SNAPSHOT.jar and there is spec jar on the proper path.
Problem is in the first "/".

If I manulay add spec jar on the wrong path all test will be passed.
```

Original comment by `kolcha...@gmail.com` on 21 Jun 2010 at 4:29

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I tried a fix but I need you to validate it on MacOS.

Thanks for trying out the latest SNAPSHOT.
```

Original comment by `etorrebo...@gmail.com` on 21 Jun 2010 at 10:26
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Thank you for the quick fix!
All is Ok with the latetest snapshot.

```

Original comment by `kolcha...@gmail.com` on 21 Jun 2010 at 3:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 21 Jun 2010 at 8:27
- Changed state: **Verified**
