### ISSUE TITLE
scala.tools.nsc.MissingRequirementError: object scala not found.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#149]
```
Scala2.8 RC3

1.edit build.xml as "Run your specification with JUnit4 and Ant" describes
2.run ant compile

error information:
[scalac] scala.tools.nsc.MissingRequirementError: object scala not found.
   [scalac]     at scala.tools.nsc.symtab.Definitions$definitions$.getModuleOrClass(Definitions.scala:512)
   [scalac]     at scala.tools.nsc.symtab.Definitions$definitions$.ScalaPackage(Definitions.scala:37)
   [scalac]     at scala.tools.nsc.symtab.Definitions$definitions$.ScalaPackageClass(Definitions.scala:38)
   [scalac]     at scala.tools.nsc.symtab.Definitions$definitions$.UnitClass(Definitions.scala:83)
   [scalac]     at scala.tools.nsc.symtab.Definitions$definitions$.init(Definitions.scala:782)
   [scalac]     at scala.tools.nsc.Global$Run.<init>(Global.scala:597)
   [scalac]     at scala.tools.ant.Scalac.executeInternal(Scalac.scala:638)
   [scalac]     at scala.tools.ant.Scalac.execute(Scalac.scala:586)
   [scalac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
   [scalac]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [scalac]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
   [scalac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
   [scalac]     at java.lang.reflect.Method.invoke(Method.java:597)
   [scalac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
   [scalac]     at org.apache.tools.ant.Task.perform(Task.java:348)
   [scalac]     at org.apache.tools.ant.Target.execute(Target.java:390)
   [scalac]     at org.apache.tools.ant.Target.performTasks(Target.java:411)
   [scalac]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1360)
   [scalac]     at org.apache.tools.ant.Project.executeTarget(Project.java:1329)
   [scalac]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
   [scalac]     at org.apache.tools.ant.Project.executeTargets(Project.java:1212)
   [scalac]     at org.apache.tools.ant.Main.runBuild(Main.java:801)
   [scalac]     at org.apache.tools.ant.Main.startAnt(Main.java:218)
   [scalac]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
   [scalac]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

Original issue reported on code.google.com by `ge.xiny...@gmail.com` on 21 Jun 2010 at 11:04

**Comment by GoogleCodeExporter** [comment]
```
Are you sure you set the repository.home variable so that the scala-library and 
scala-compiler jars can be found?
```

Original comment by `etorrebo...@gmail.com` on 21 Jun 2010 at 11:44

**Comment by GoogleCodeExporter** [comment]
```
I used a wrong version Specs
Thanks.
```

Original comment by `ge.xiny...@gmail.com` on 24 Jun 2010 at 1:18

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 24 Jun 2010 at 1:32
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
i have the save err.
i use brew install scala, at idea,i set the compiler.

 scala.tools.nsc.MissingRequirementError: object scala not found....
```

Original comment by `SoftH...@gmail.com` on 2 Feb 2012 at 1:20

**Comment by GoogleCodeExporter** [comment]
```
You're using IDEA? Which version?

Again, I don't think this has anything to do with specs but more about how the 
scala library can be found to run your scala program. Can you run a simple 
"Hello world" program? Can you run a JUnit test implemented as a Scala class?
```

Original comment by `etorrebo...@gmail.com` on 2 Feb 2012 at 1:36
