### ISSUE TITLE
java.lang.NoSuchMethodError in specs-1.6.1-2.8.0.Beta1-RC6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#151]
```
I am using Scala 2.8.0 RC6 and Specs 1.6.1-2.8.0 Beta1-RC6.  I created a simple 
specification just to test if the latest Specs beta works on the latest Scala 
version.  Unfortunately already in the main method the following exception is 
thrown:

Exception in thread "main" java.lang.NoSuchMethodError: 
scala.collection.TraversableLike.$plus$plus(Lscala/collection/Traversable;Lscala
/collection/generic/CanBuildFrom;)Ljava/lang/Object;
    at org.specs.runner.Reporter$class.main(Reporter.scala:122)
    at org.specs.Specification.main(Specification.scala:43)
    at scaup.text.spec.DiffSpec.main(DiffSpec.scala)
Java Result: 1

Any suggestions?

Cheers,
Normen


```

Original issue reported on code.google.com by `normen.m...@gmail.com` on 27 Jun 2010 at 10:44

**Comment by GoogleCodeExporter** [comment]
```
We're not talking about the same RC6 here. The one you tried is specs for scala 
Beta1.RC6. The one you need for the latest Scala release is:

http://scala-tools.org/repo-snapshots/org/scala-tools/testing/specs_2.8.0.RC6/1.
6.5-SNAPSHOT/
```

Original comment by `etorrebo...@gmail.com` on 27 Jun 2010 at 11:15
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
Ops.. thanks for clarification!
```

Original comment by `normen.m...@gmail.com` on 27 Jun 2010 at 12:15
