### ISSUE TITLE
assertions done in doBefore cause PathException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#152]
```
Any assertions done in doBefore cause the spec to throw PathException. Example:

object AssertionsInDoBeforeSpec extends Specification{
  "The spec" should{
    doBefore(1 mustBe 1)
    "run nicely regardless of assertions done in doBefore" in{
      1 mustBe 1
    }
  }
}

Running that example causes:

Exception in thread "main" org.specs.specification.PathException: 
TreePath(List(0, 1, 0))not found for example 1
    at org.specs.specification.SpecificationExecutor$class.executeExample(SpecificationExecutor.scala:52)
    at org.specs.specification.BaseSpecification.executeExample(BaseSpecification.scala:58)
    at org.specs.specification.BaseSpecification.executeExample(BaseSpecification.scala:58)
    at org.specs.specification.ExampleLifeCycle$$anonfun$executeExample$1.apply(ExampleLifeCycle.scala:117)
    at org.specs.specification.ExampleLifeCycle$$anonfun$executeExample$1.apply(ExampleLifeCycle.scala:117)
    at scala.Option.map(Option.scala:74)
    at org.specs.specification.ExampleLifeCycle$class.executeExample(ExampleLifeCycle.scala:117)
    at org.specs.specification.Examples.executeExample(Examples.scala:52)
    at org.specs.specification.Examples.executeExample(Examples.scala:52)
    at org.specs.specification.Examples$$anonfun$executeExamples$1.apply(Examples.scala:80)
    at org.specs.specification.Examples$$anonfun$executeExamples$1.apply(Examples.scala:80)
    at scala.Option.map(Option.scala:74)
    at org.specs.specification.Examples.executeExamples(Examples.scala:80)
    at org.specs.specification.ExampleStructure$class.examples(ExampleStructure.scala:77)
    at org.specs.specification.Examples.examples(Examples.scala:52)
    at org.specs.runner.OutputReporter$class.stats(ConsoleReporter.scala:128)
    at org.specs.Specification.stats(Specification.scala:43)
    at org.specs.runner.OutputReporter$$anonfun$stats$3.apply(ConsoleReporter.scala:119)
    at org.specs.runner.OutputReporter$$anonfun$stats$3.apply(ConsoleReporter.scala:119)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:123)
    at scala.collection.immutable.List.foldLeft(List.scala:45)
    at org.specs.runner.OutputReporter$class.stats(ConsoleReporter.scala:119)
    at org.specs.Specification.stats(Specification.scala:43)
    at org.specs.runner.OutputReporter$$anonfun$stats$1.apply(ConsoleReporter.scala:110)
    at org.specs.runner.OutputReporter$$anonfun$stats$1.apply(ConsoleReporter.scala:110)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:123)
    at scala.collection.immutable.List.foldLeft(List.scala:45)
    at org.specs.runner.OutputReporter$class.stats(ConsoleReporter.scala:110)
    at org.specs.Specification.stats(Specification.scala:43)
    at org.specs.runner.OutputReporter$class.reportSpec(ConsoleReporter.scala:96)
    at org.specs.Specification.reportSpec(Specification.scala:43)
    at org.specs.runner.OutputReporter$$anonfun$report$1.apply(ConsoleReporter.scala:74)
    at org.specs.runner.OutputReporter$$anonfun$report$1.apply(ConsoleReporter.scala:74)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at org.specs.runner.OutputReporter$class.report(ConsoleReporter.scala:74)
    at org.specs.Specification.report(Specification.scala:43)
    at org.specs.runner.OutputReporter$class.report(ConsoleReporter.scala:65)
    at org.specs.Specification.report(Specification.scala:43)
    at org.specs.Specification.report(Specification.scala:43)
    at org.specs.runner.Reporter$class.reportSpecs(Reporter.scala:195)
    at org.specs.Specification.reportSpecs(Specification.scala:43)
    at org.specs.runner.Reporter$class.main(Reporter.scala:140)
    at org.specs.Specification.main(Specification.scala:43)

The version used is specs_2.8.0.RC6-1.6.5-SNAPSHOT.jar from 23.6.2010. As far 
as I know that is the latest available snapshot for 2.8 (got it from 
http://scala-tools.org/repo-snapshots/org/scala-tools/testing/specs_2.8.0.RC6/1.
6.5-SNAPSHOT/ )
```

Original issue reported on code.google.com by `saynomoo@gmail.com` on 30 Jun 2010 at 1:35

**Comment by GoogleCodeExporter** [comment]
```
For now I'm using following workaround: 

trait AssertionsInDoBeforeWorkaround extends Specification{
  override def executeExample(example: Examples) = try{
    super.executeExample(example)
  }catch{
    case e: PathException => {
      println(e)
      example.executeThis
      this
    }
  }
}


```

Original comment by `saynomoo@gmail.com` on 30 Jun 2010 at 2:04

**Comment by GoogleCodeExporter** [comment]
```
Hi, this issue should be fixed with the latest release: 
http://nexus.scala-tools.org/content/repositories/snapshots/org/scala-tools/test
ing/specs_2.8.0.RC7/1.6.5-SNAPSHOT.

(note the RC7, I've upgraded to Scala.2.8.0.RC7 too, I hope that's ok with you)
```

Original comment by `etorrebo...@gmail.com` on 1 Jul 2010 at 3:23
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the really quick response! The latest snapshot works nicely.
```

Original comment by `saynomoo@gmail.com` on 1 Jul 2010 at 7:43

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 1 Jul 2010 at 8:08
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 31 Mar 2011 at 8:05
- Added labels: **mutable**
