### ISSUE TITLE
Defining a beforeContext block with val after spec definition causes specs to crash with NullPointerException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#187]
```
What steps will reproduce the problem?
1. Have specs_2.8.1-1.6.7.jar in the classpath
2. Compile the attached SpecsBugReproducingSpec
3. Run with "scala SpecsBugReproducingSpec"



What is the expected output? What do you see instead?

Expected:
---------
Specification "SpecsBugReproducingSpec"
  test should
  o not crash
    PENDING: not yet implemented (ConsoleReporter.scala:223)

Total for specification "SpecsBugReproducingSpec":
Finished in 0 second, 80 ms
1 example (1 skipped), 0 expectation, 0 failure, 0 error
---------

Actual:
---------
Specification "SpecsBugReproducingSpec"
  test should
java.lang.NullPointerException
    at org.specs.specification.Contexts$$anonfun$org$specs$specification$Contexts$$transferActionsToSus$1.apply$mcZ$sp(Context.scala:221)
    at org.specs.specification.LifeCycle$class.until(ExampleLifeCycle.scala:78)
    at org.specs.specification.Examples.until(Examples.scala:52)
    at org.specs.specification.ExampleExecution$$anonfun$2$$anonfun$apply$4.apply(ExampleLifeCycle.scala:182)
    at org.specs.specification.ExampleExecution$$anonfun$2$$anonfun$apply$4.apply(ExampleLifeCycle.scala:182)
    at scala.Option.map(Option.scala:129)
    at org.specs.specification.ExampleExecution$$anonfun$2.apply(ExampleLifeCycle.scala:182)
    at org.specs.specification.ExampleExecution.execute(ExampleLifeCycle.scala:252)
    at org.specs.specification.SpecificationExecutor$$anonfun$executeExample$3.apply(SpecificationExecutor.scala:70)
    at org.specs.specification.SpecificationExecutor$$anonfun$executeExample$3.apply(SpecificationExecutor.scala:70)
    at scala.Option.map(Option.scala:129)
    at org.specs.specification.SpecificationExecutor$class.executeExample(SpecificationExecutor.scala:70)
    at org.specs.specification.BaseSpecification.executeExample(BaseSpecification.scala:58)
    at org.specs.specification.BaseSpecification.executeExample(BaseSpecification.scala:58)
    at org.specs.specification.ExampleLifeCycle$$anonfun$executeExample$1.apply(ExampleLifeCycle.scala:125)
    at org.specs.specification.ExampleLifeCycle$$anonfun$executeExample$1.apply(ExampleLifeCycle.scala:125)
    at scala.Option.map(Option.scala:129)
    at org.specs.specification.ExampleLifeCycle$class.executeExample(ExampleLifeCycle.scala:125)
    at org.specs.specification.Examples.executeExample(Examples.scala:52)
    at org.specs.specification.Examples.executeExample(Examples.scala:52)
    at org.specs.specification.Examples$$anonfun$executeExamples$2.apply(Examples.scala:80)
    at org.specs.specification.Examples$$anonfun$executeExamples$2.apply(Examples.scala:80)
    at scala.Option.map(Option.scala:129)
    at org.specs.specification.Examples.executeExamples(Examples.scala:80)
    at org.specs.specification.ExampleStructure$class.ownFailures(ExampleStructure.scala:58)
    at org.specs.specification.Examples.ownFailures(Examples.scala:52)
    at org.specs.specification.ExampleStructure$class.failures(ExampleStructure.scala:64)
    at org.specs.specification.Examples.failures(Examples.scala:52)
    at org.specs.specification.Examples.failures(Examples.scala:52)
    at org.specs.execute.HasResults$class.failureAndErrors(HasResults.scala:61)
    at org.specs.specification.Examples.failureAndErrors(Examples.scala:52)
    at org.specs.execute.HasResults$class.hasFailureOrErrors(HasResults.scala:59)
    at org.specs.specification.Examples.hasFailureOrErrors(Examples.scala:52)
    at org.specs.runner.OutputReporter$class.status$1(ConsoleReporter.scala:223)
    at org.specs.runner.OutputReporter$class.reportExample(ConsoleReporter.scala:232)
    at org.specs.Specification.reportExample(Specification.scala:43)
    at org.specs.runner.OutputReporter$$anonfun$reportExamples$1.apply(ConsoleReporter.scala:210)
    at org.specs.runner.OutputReporter$$anonfun$reportExamples$1.apply(ConsoleReporter.scala:209)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at org.specs.runner.OutputReporter$class.reportExamples(ConsoleReporter.scala:209)
    at org.specs.Specification.reportExamples(Specification.scala:43)
    at org.specs.runner.OutputReporter$class.printSus(ConsoleReporter.scala:174)
    at org.specs.Specification.printSus(Specification.scala:43)
    at org.specs.runner.OutputReporter$class.displaySus$1(ConsoleReporter.scala:141)
    at org.specs.runner.OutputReporter$$anonfun$reportSystems$1.apply(ConsoleReporter.scala:147)
    at org.specs.runner.OutputReporter$$anonfun$reportSystems$1.apply(ConsoleReporter.scala:142)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at org.specs.runner.OutputReporter$class.reportSystems(ConsoleReporter.scala:142)
    at org.specs.Specification.reportSystems(Specification.scala:43)
    at org.specs.runner.OutputReporter$class.reportSpec(ConsoleReporter.scala:87)
    at org.specs.Specification.reportSpec(Specification.scala:43)
    at org.specs.runner.OutputReporter$$anonfun$report$1.apply(ConsoleReporter.scala:74)
    at org.specs.runner.OutputReporter$$anonfun$report$1.apply(ConsoleReporter.scala:74)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at org.specs.runner.OutputReporter$class.report(ConsoleReporter.scala:74)
    at org.specs.Specification.report(Specification.scala:43)
    at org.specs.runner.OutputReporter$class.report(ConsoleReporter.scala:65)
    at org.specs.Specification.report(Specification.scala:43)
    at org.specs.Specification.report(Specification.scala:43)
    at org.specs.runner.Reporter$class.reportSpecs(Reporter.scala:195)
    at org.specs.Specification.reportSpecs(Specification.scala:43)
    at org.specs.runner.Reporter$class.main(Reporter.scala:140)
    at org.specs.Specification.main(Specification.scala:43)
    at SpecsBugReproducingSpec.main(SpecsBugReproducingSpec.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:81)
    at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:24)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:86)
    at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:81)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:86)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:83)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
---------



What version of the product are you using? On what operating system?

specs_2.8.1-1.6.7.jar from the Google Code downloads. Reproducible both on Mac 
OS X 10.6.8 and Ubuntu 10.04 with Scala 2.8.1



Please provide any additional information below.

Seems to be reproducible with specs_2.8.1-1.6.8 (from Maven sources), too.

There are two other specs in the attached file that are slightly different and 
pass properly: SpecsBugNonReproducingSpec1, SpecsBugNonReproducingSpec2

```

Original issue reported on code.google.com by `eemeli.k...@gmail.com` on 6 Sep 2011 at 12:25

Attachments:
- [SpecsBugReproducingSpec.scala](https://storage.googleapis.com/google-code-attachments/specs/issue-187/comment-0/SpecsBugReproducingSpec.scala)

**Comment by GoogleCodeExporter** [comment]
```
The original attachment is slightly broken, here's a new one.
```

Original comment by `eemeli.k...@gmail.com` on 6 Sep 2011 at 12:28

Attachments:
- [SpecsBugReproducingSpec.scala](https://storage.googleapis.com/google-code-attachments/specs/issue-187/comment-1/SpecsBugReproducingSpec.scala)

**Comment by GoogleCodeExporter** [comment]
```
I don't think there's anything I can do about that. I guess that this is the 
result of Scala's initialisation of members and code blocks inside a class.

If your objective is to keep a val at the end of the specification, you can use 
a lazy val instead of a simple val.
```

Original comment by `etorrebo...@gmail.com` on 6 Sep 2011 at 10:09
- Changed state: **WontFix**
