### ISSUE TITLE
Error on HelloWorld example: java.lang.NoClassDefFoundError: scala/Serializable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#188]
```
What steps will reproduce the problem?
1. Installed scala with apt-get install scala
2. Created a HelloWorld.scala file with the contents detailed in the User Guide
3. Downloaded the latest specs .jar file and put it next to my HelloWorld.scala 
file
4. Executed scala -cp spec-version.jar HelloWorld.scala

What is the expected output? What do you see instead?

The expected output was the one shown in the User guide (a simple spec being 
tested and passing). Instead, I got a lengthy error message (Including full 
trace at the end of this report).


What version of the product are you using? On what operating system?

specs: 2.9.1-1.6.9
scala: Scala version 2.7.7final (OpenJDK 64-Bit Server VM, Java 1.6.0_22)
Operative system: ubuntu 11.04


Please provide any additional information below.

I've done some googling and apparently this error happens because "the jvm 
can't find the scala classes" - or something on that line. I believe this is 
related to the -cp option used on the scala argument - for which I could find 
no explanation or info.

I hereby request that the User guide explains how to run the basic example with 
a bit more detail.

Full stack trace follows:
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Serializable
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2444)
    at java.lang.Class.getMethod0(Class.java:2687)
    at java.lang.Class.getMethod(Class.java:1620)
    at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:70)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:154)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
Caused by: java.lang.ClassNotFoundException: scala.Serializable
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    ... 17 more





```

Original issue reported on code.google.com by `kik...@gmail.com` on 22 Oct 2011 at 10:25

**Comment by GoogleCodeExporter** [comment]
```
The versions of specs and scala you indicate are not compatible:

specs: 2.9.1-1.6.9
scala: Scala version 2.7.7final

specs is using Scala 2.9.1 so you should be using the same version. In your 
case, the scala library is found but does not contain the expected classes.

Also if you are starting a new project, I advise you to have a look at specs2 
instead: http://specs2.org
```

Original comment by `etorrebo...@gmail.com` on 22 Oct 2011 at 10:54
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
Wow, very fast answer. I was going to modify this to point out that I had found 
out about specs2.

I've created a SO question and posted it to the user group; I'm a bit confused 
on how to use it; the user guide seems to imply certain previous knowledge that 
I lack.

I didn't know that my default scala instalation was so dated. I will have to 
check that one out.

Thanks in any case.
```

Original comment by `kik...@gmail.com` on 22 Oct 2011 at 11:07
