### ISSUE TITLE
Clarify required JUnit version.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#36]
```
From the documentation I get the impression that specs works with any JUnit
4 version, but using specs with JUnit < 4.4, which is what is bundled with
Eclipse and NetBeans, gives the error below. A notice on the wiki (and a
useful error message) that 4.4 is required would be nice.

java.lang.NoSuchMethodError:
org.junit.runner.Description.createSuiteDescription(Ljava/lang/String;[Ljava/lan
g/annotation/Annotation;)Lorg/junit/runner/Description;
    at
org.specs.runner.TestDescription$class.asDescription(JUnitSuiteRunner.scala:79)
    at org.specs.runner.JUnitSuiteRunner.asDescription(JUnitSuiteRunner.scala:13)
    at
org.specs.runner.TestDescription$class.makeDescription(JUnitSuiteRunner.scala:87
)
    at
org.specs.runner.JUnitSuiteRunner.makeDescription(JUnitSuiteRunner.scala:13)
    at org.specs.runner.JUnitSuiteRunner.getDescription(JUnitSuiteRunner.scala:37)
    at org.junit.runner.Runner.testCount(Runner.java:38)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.countTestCases(J
Unit4TestClassReference.java:29)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.countTests(RemoteTestRunn
er.java:480)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:448)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:673)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java
:386)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.jav
a:196)

```

Original issue reported on code.google.com by `eskil.by...@gmail.com` on 25 Aug 2008 at 8:08

**Comment by GoogleCodeExporter** [comment]
```
I've added a new section in "Running specs" listing all dependencies: 
http://code.google.com/p/specs/wiki/RunningSpecs#Dependencies
```

Original comment by `etorrebo...@gmail.com` on 1 Sep 2008 at 5:51
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 25 Feb 2009 at 9:37
- Changed state: **Verified**
