### ISSUE TITLE
Add specs 1.4.4 to maven repository.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#66]
```
Specs 1.4.4 is not in the maven repository yet. I assume that this is due
to the server difficulties they had last week, so I am filing this here to
remind Eric to do it whenever he has the chance. :)


```

Original issue reported on code.google.com by `ismaelj` on 14 Apr 2009 at 3:28

**Comment by GoogleCodeExporter** [comment]
```
The server is still not accessible to upload jars.

In the meantime you can access them by adding this repository to your pom file:

<!-- This should be added to the repositories section -->
    <repository>
      <id>specs-repo</id>
      <name>specs repository</name>
      <layout>default</layout>
      http://specs.googlecode.com/svn/maven2/
      <releases>
        <checksumPolicy>ignore</checksumPolicy>
      </releases>
      <snapshots>
        <checksumPolicy>ignore</checksumPolicy>
      </snapshots>
    </repository>

And make sure that you reference the proper groupId which has just been 
changed: 

org.scala-tools.testing:specs:1.4.4

Eric.
```

Original comment by `etorrebo...@gmail.com` on 14 Apr 2009 at 10:05
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Thanks Eric. Btw, not sure if you noticed, but 1.4.3 is actually available 
under that
group id in scala-tools (in addition to the old one):

http://scala-tools.org/repo-releases/org/scala-tools/testing/specs/
```

Original comment by `ismaelj` on 14 Apr 2009 at 10:12

**Comment by GoogleCodeExporter** [comment]
```
No I didn't notice that. I think that David Bernard did the migration when we 
decided 
to use that groupId for both specs, ScalaTest and ScalaCheck.

I'm leaving this issue open until the moment I'm able to upload the jars again.
```

Original comment by `etorrebo...@gmail.com` on 15 Apr 2009 at 12:52

**Comment by GoogleCodeExporter** [comment]
```
The repository listed doesn't work if copied directly from a browser. There may 
be
some wiki markup trickery in play. Make sure you surround
http://specs.googlecode.com/svn/maven2 with <url> tags
```

Original comment by `tony.hil...@gmail.com` on 18 Apr 2009 at 11:49

**Comment by GoogleCodeExporter** [comment]
```
WHen I add the repository listed here, I get the following error on test:

[WARNING] Exception in thread "main" java.lang.RuntimeException: malformed Scala
signature of MocksCreation at 1706; reference type Manifest of package reflect 
refers
to nonexisting symbol.
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.errorBadSignature(UnPickler.
scala:755)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.scala$tools$nsc$symtab$class
file$UnPickler$UnPickle$$readSymbol(UnPickler.scala:172)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$$anonfun$scala$tools$nsc$sym
tab$classfile$UnPickler$UnPickle$$readSymbolRef$1.apply(UnPickler.scala:707)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$$anonfun$scala$tools$nsc$sym
tab$classfile$UnPickler$UnPickle$$readSymbolRef$1.apply(UnPickler.scala:707)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.scala$tools$nsc$symtab$class
file$UnPickler$UnPickle$$at(UnPickler.scala:139)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.scala$tools$nsc$symtab$class
file$UnPickler$UnPickle$$readSymbolRef(UnPickler.scala:707)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.scala$tools$nsc$symtab$class
file$UnPickler$UnPickle$$readType(UnPickler.scala:253)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$$anonfun$scala$tools$nsc$sym
tab$classfile$UnPickler$UnPickle$$readTypeRef$1.apply(UnPickler.scala:708)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$$anonfun$scala$tools$nsc$sym
tab$classfile$UnPickler$UnPickle$$readTypeRef$1.apply(UnPickler.scala:708)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.scala$tools$nsc$symtab$class
file$UnPickler$UnPickle$$at(UnPickler.scala:139)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.scala$tools$nsc$symtab$class
file$UnPickler$UnPickle$$readTypeRef(UnPickler.scala:708)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$$anonfun$scala$tools$nsc$sym
tab$classfile$UnPickler$UnPickle$$readType$4.apply(UnPickler.scala:274)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$$anonfun$scala$tools$nsc$sym
tab$classfile$UnPickler$UnPickle$$readType$4.apply(UnPickler.scala:274)
[WARNING]   at 
scala.tools.nsc.symtab.classfile.PickleBuffer.until(PickleBuffer.scala:127)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.scala$tools$nsc$symtab$class
file$UnPickler$UnPickle$$readType(UnPickler.scala:274)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$$anonfun$scala$tools$nsc$sym
tab$classfile$UnPickler$UnPickle$$readTypeRef$1.apply(UnPickler.scala:708)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$$anonfun$scala$tools$nsc$sym
tab$classfile$UnPickler$UnPickle$$readTypeRef$1.apply(UnPickler.scala:708)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.scala$tools$nsc$symtab$class
file$UnPickler$UnPickle$$at(UnPickler.scala:139)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.scala$tools$nsc$symtab$class
file$UnPickler$UnPickle$$readTypeRef(UnPickler.scala:708)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.scala$tools$nsc$symtab$class
file$UnPickler$UnPickle$$readType(UnPickler.scala:276)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$LazyTypeRef$$anonfun$31$$ano
nfun$apply$4.apply(UnPickler.scala:772)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$LazyTypeRef$$anonfun$31$$ano
nfun$apply$4.apply(UnPickler.scala:772)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle.scala$tools$nsc$symtab$class
file$UnPickler$UnPickle$$at(UnPickler.scala:139)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$LazyTypeRef$$anonfun$31.appl
y(UnPickler.scala:772)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$LazyTypeRef$$anonfun$31.appl
y(UnPickler.scala:772)
[WARNING]   at scala.tools.nsc.Global$$anonfun$7.apply(Global.scala:708)
[WARNING]   at scala.tools.nsc.Global$$anonfun$7.apply(Global.scala:708)
[WARNING]   at
scala.tools.nsc.symtab.classfile.UnPickler$UnPickle$LazyTypeRef.complete(UnPickl
er.scala:772)
[WARNING]   at scala.tools.nsc.symtab.Symbols$Symbol.info(Symbols.scala:492)
[WARNING]   at scala.tools.nsc.symtab.Symbols$Symbol.tpe(Symbols.scala:471)
[WARNING]   at scala.tools.nsc.symtab.Symbols$Symbol.tpeHK(Symbols.scala:621)
[WARNING]   at scala.tools.nsc.symtab.Types$Type.memberType(Types.scala:407)
[WARNING]   at
scala.tools.nsc.typechecker.Infer$Inferencer.checkAccessible(Infer.scala:361)
[WARNING]   at 
scala.tools.nsc.typechecker.Typers$Typer.typedIdent$1(Typers.scala:2823)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3096)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:3167)
[WARNING]   at
scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedApply$1$1.apply(Typers.sc
ala:2465)
[WARNING]   at
scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedApply$1$1.apply(Typers.sc
ala:2465)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:556)
[WARNING]   at 
scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:2465)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3064)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:3167)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:3215)
[WARNING]   at 
scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:3257)
[WARNING]   at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:825)
[WARNING]   at
scala.tools.nsc.typechecker.Namers$Namer$$anonfun$typeCompleter$1.apply(Namers.s
cala:403)
[WARNING]   at
scala.tools.nsc.typechecker.Namers$Namer$$anonfun$typeCompleter$1.apply(Namers.s
cala:401)
[WARNING]   at 
scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:987)
[WARNING]   at scala.tools.nsc.symtab.Symbols$Symbol.info(Symbols.scala:492)
[WARNING]   at 
scala.tools.nsc.symtab.Symbols$Symbol.initialize(Symbols.scala:602)
[WARNING]   at 
scala.tools.nsc.typechecker.Typers$Typer.addGetterSetter(Typers.scala:1076)
[WARNING]   at
scala.tools.nsc.typechecker.Typers$Typer$$anonfun$10.apply(Typers.scala:1151)
[WARNING]   at
scala.tools.nsc.typechecker.Typers$Typer$$anonfun$10.apply(Typers.scala:1151)
[WARNING]   at scala.List.flatMap(List.scala:1046)
[WARNING]   at 
scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1151)
[WARNING]   at 
scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1051)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:2899)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:3167)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:3204)
[WARNING]   at 
scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:1515)
[WARNING]   at
scala.tools.nsc.typechecker.Typers$Typer$$anonfun$19.apply(Typers.scala:1560)
[WARNING]   at
scala.tools.nsc.typechecker.Typers$Typer$$anonfun$19.apply(Typers.scala:1560)
[WARNING]   at scala.List$.loop$1(List.scala:254)
[WARNING]   at scala.List$.mapConserve(List.scala:271)
[WARNING]   at scala.List$.loop$1(List.scala:258)
[WARNING]   at scala.List$.mapConserve(List.scala:271)
[WARNING]   at scala.List$.loop$1(List.scala:258)
[WARNING]   at scala.List$.mapConserve(List.scala:271)
[WARNING]   at scala.List$.loop$1(List.scala:258)
[WARNING]   at scala.List$.mapConserve(List.scala:271)
[WARNING]   at scala.List$.loop$1(List.scala:258)
[WARNING]   at scala.List$.mapConserve(List.scala:271)
[WARNING]   at scala.List$.loop$1(List.scala:258)
[WARNING]   at scala.List$.mapConserve(List.scala:271)
[WARNING]   at 
scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:1560)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:2892)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:3167)
[WARNING]   at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:3204)
[WARNING]   at
scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$2.apply(Analyzer.scala:4
0)
[WARNING]   at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:247)
[WARNING]   at 
scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:233)
[WARNING]   at 
scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:233)
[WARNING]   at scala.Iterator$class.foreach(Iterator.scala:387)
[WARNING]   at 
scala.collection.mutable.ListBuffer$$anon$1.foreach(ListBuffer.scala:255)
[WARNING]   at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:233)
[WARNING]   at scala.tools.nsc.Global$Run.compileSources(Global.scala:545)
[WARNING]   at scala.tools.nsc.Global$Run.compile(Global.scala:629)
[WARNING]   at scala.tools.nsc.Main$.process(Main.scala:86)
[WARNING]   at scala.tools.nsc.Main$.main(Main.scala:107)
[WARNING]   at scala.tools.nsc.Main.main(Main.scala)

```

Original comment by `tony.hil...@gmail.com` on 18 Apr 2009 at 11:50

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Sorry, that was rude. Added a new ticket ticket:69
```

Original comment by `tony.hil...@gmail.com` on 19 Apr 2009 at 12:02

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 27 Apr 2009 at 5:14
- Changed state: **Verified**
