### ISSUE TITLE
skip in "in" clause throws exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#72]
```
It would be nice if it worked, but if not, then it should not fail at
runtime like that.

package stest;

import org.specs.Specification;
import org.specs.runner.JUnit4;

class FooTest extends JUnit4(new Specification("Foo") {

  "foo" should {
    "bar" in {
      skip("not ready")
      0 must be_==(0)
    }
  }
})

org.specs.runner.ContextualizedThrowable: not ready
    at stest.FooTest$$anon$1$$anonfun$1$$anonfun$apply$1.apply(FooTest.scala:10)
    at stest.FooTest$$anon$1$$anonfun$1$$anonfun$apply$1.apply(FooTest.scala:9)
    at
org.specs.specification.ExampleExecution$$anonfun$3$$anonfun$apply$1.apply(Examp
le.scala:207)
    at org.specs.specification.Example.execute(Example.scala:121)
    at
org.specs.specification.ExampleLifeCycle$class.executeTest(ExampleLifeCycle.scal
a:20)
    at org.specs.Specification.executeTest(Specification.scala:28)
    at org.specs.specification.Sus.executeTest(Sus.scala:147)
    at
org.specs.specification.ExampleExecution$$anonfun$3.apply(Example.scala:207)
    at
org.specs.specification.ExampleExecution$$anonfun$3.apply(Example.scala:194)
    at
org.specs.specification.ExampleExecution$$anonfun$2.apply(Example.scala:185)
    at org.specs.specification.ExampleExecution.execute(Example.scala:227)
    at org.specs.specification.Example.execute(Example.scala:117)
    at org.specs.specification.Example.ownFailures(Example.scala:135)
    at org.specs.runner.ExampleTestCase.report$1(JUnit.scala:163)
    at org.specs.runner.ExampleTestCase.run(JUnit.scala:176)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.specs.runner.JUnitSuite$class.run(JUnit.scala:42)
    at org.specs.runner.ExamplesTestSuite.run(JUnit.scala:148)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.specs.runner.JUnitSuite$class.run(JUnit.scala:42)
    at org.specs.runner.JUnit4.run(JUnit.scala:110)
    at
org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:81)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReferen
ce.java:45)
    at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:460)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:673)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java
:386)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.jav
a:196)


```

Original issue reported on code.google.com by `ismaelj` on 1 May 2009 at 7:09

**Comment by GoogleCodeExporter** [comment]
```
I forgot to mention that I tested it with Specs 1.4.4.
```

Original comment by `ismaelj` on 1 May 2009 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
Can you please try with the latest version 1.5.0-SNAPSHOT, because I can't 
reproduce 
it with that version?



```

Original comment by `etorrebo...@gmail.com` on 1 May 2009 at 7:57
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
With 1.5.0-SNAPSHOT, I now get:

org.specs.runner.UserError: org.specs.execute.SkippedException: not ready

This is better and maybe the best that can be done. I'd prefer if the example 
was
skipped instead of throwing an error though. It seems natural to use the same
construct to skip both "should" and "in" clauses.
```

Original comment by `ismaelj` on 1 May 2009 at 8:35

**Comment by GoogleCodeExporter** [comment]
```
Can you please tell me where / how you get the stacktrace?

Here is a picture of what I got in Eclipse, the test is ignored as expected.
```

Original comment by `etorrebo...@gmail.com` on 1 May 2009 at 9:28

Attachments:
- [issue72.png](https://storage.googleapis.com/google-code-attachments/specs/issue-72/comment-4/issue72.png)

**Comment by GoogleCodeExporter** [comment]
```
That is odd. I usually use a JUnit runner that runs all the tests in the 
project, but
for this I used a SingleTestJUnitRunner. Maybe that's the issue. I wasn't aware 
that
one could run Specifications directly now. Does that require some configuration 
in
Eclipse? If so, is that documented somewhere?

Screenshot attached.
```

Original comment by `ismaelj` on 1 May 2009 at 9:53

Attachments:
- [issue72.png](https://storage.googleapis.com/google-code-attachments/specs/issue-72/comment-5/issue72.png)

**Comment by GoogleCodeExporter** [comment]
```
Eclipse should be able to find your test classes if you do this:

http://code.google.com/p/specs/wiki/RunningSpecs#Run_your_specification_with_JUn
it4_i
n_Eclipse.

Make sure that you specify JUnit4 as the runner and that should be ok.
```

Original comment by `etorrebo...@gmail.com` on 1 May 2009 at 12:55

**Comment by GoogleCodeExporter** [comment]
```
Thanks. For some reason, the instructions in that link did not work for me. In 
any
case, when I tried my JUnit4 runner (which runs all the tests in a given 
project)
with Specs 1.5.0-SNAPSHOT, skip indeed works correctly inside in clauses. So 
this bug
can be closed.
```

Original comment by `ismaelj` on 2 May 2009 at 8:10

**Comment by GoogleCodeExporter** [comment]
```
Great. I close it then
```

Original comment by `etorrebo...@gmail.com` on 2 May 2009 at 9:17
- Changed state: **Verified**
