### ISSUE TITLE
Specs should not mask exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#73]
```
package stest;

import org.specs.Specification;
import org.specs.runner.JUnit4;

class FooTest extends JUnit4(new Specification("Foo") {
  "foo" should {
    "bar" in {
      (new A).m must be_==("foo")
    }
  }
})

class A {
  def m: String = error("error")
}

Top of the output in Eclipse JUnit Runner:

org.specs.runner.ContextualizedThrowable: error
    at scala.Predef$.error(Predef.scala:76)
    at stest.A.m(FooTest.scala:15)
    at
stest.FooTest$$anon$1$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(FooTest
.scala:9)
    at
stest.FooTest$$anon$1$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(FooTest
.scala:9)

The fact that it's an IllegalArgumentException is missing.

Another example:

package stest;

import org.specs.Specification;
import org.specs.runner.JUnit4;

class FooTest extends JUnit4(new Specification("Foo") {
  "foo" should {
    "bar" in {
      (new A).m must be_==("foo")
    }
  }
})

class A {
  def m: String = null.toString
}

org.specs.runner.ContextualizedThrowable: null
    at stest.A.m(FooTest.scala:15)
    at
stest.FooTest$$anon$1$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(FooTest
.scala:9)
    at
stest.FooTest$$anon$1$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(FooTest
.scala:9)
    at org.specs.matcher.AnyMatchers$$anon$2.apply(AnyMatchers.scala:62)

Why not just show the original exception?

Tested with Specs 1.4.4.
```

Original issue reported on code.google.com by `ismaelj` on 1 May 2009 at 7:29

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report.

This is fixed in specs-1.5.0-SNAPSHOT (http://scala-tools.org/repo-
snapshots/org/scala-tools/testing/specs/1.5.0-SNAPSHOT/).

Please verify if it's ok with you.

Thanks.
```

Original comment by `etorrebo...@gmail.com` on 1 May 2009 at 7:58
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Thanks, it works great there indeed.

Do you have an ETA for the release of 1.5.0? This bug is highly annoying as it 
means
I have to wrap my tests in try/catch blocks whenever an exception is thrown 
while the
test is running.
```

Original comment by `ismaelj` on 1 May 2009 at 8:39

**Comment by GoogleCodeExporter** [comment]
```
I would like to polish a little bit more my Forms stuff but I was planning to 
do that 
during next week anyway.
```

Original comment by `etorrebo...@gmail.com` on 1 May 2009 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
Thanks Eric.
```

Original comment by `ismaelj` on 1 May 2009 at 6:03

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 14 Feb 2010 at 2:43
- Changed state: **Verified**
